### ISSUE TITLE
Area Skills hit ally!

### ISSUE THREAD

**Issue by SnUncle** [Eniripsa96/SkillAPI#180] opened 2017-10-08 07:35 UTC
I set the group of target  "enemy" 
but the skill hit myself and my ally why ?

and i invited my ally in my party but he still get damage

this is my config 

plz help me !

Targeting: 

  # Whether or not all monsters are enemies.
  # If you are using pets that include zombies/spiders/etc,
  # you shouldn't enable this.
  # If you want to enable it for specific worlds, list out the
  # worlds it should apply to in a list format such as:
  # monsters-enemy:
  # - world1
  # - world2
  monsters-enemy: 'true'

  # Whether or not all passive mobs are allies.
  # If there are custom passive mobs that you can fight,
  # you should not enable this.
  # If you want to enable it for specific worlds, list out the
  # worlds it should apply to in a list format such as:
  # passive-ally:
  # - world1
  # - world2
  passive-ally: 'false'

  # Whether or not all players are allies.
  # If you have any PvP, this should not be enabled.
  # If you want to enable it for specific worlds, list out the
  # worlds it should apply to in a list format such as:
  # player-ally:
  # - world1
  # - world2
  player-ally: 'false'

  # Whether or not to check for player allies via Parties
  parties-ally: 'true'

**Comment by SnUncle** [comment] 2017-10-08 07:43
不死人进行曲: 
  name: '不死人进行曲'
  type: '范围技能'
  max-level: 5
  skill-req-lvl: 0
  needs-permission: 'false'
  attributes: 
    level-base: '1'
    level-scale: '1'
    cost-base: '1'
    cost-scale: '1'
    cooldown-base: '0'
    cooldown-scale: '0'
    mana-base: '0'
    mana-scale: '0'
    points-spent-req-base: '0'
    points-spent-req-scale: '0'
    incompatible: 
    - ''
  msg: '&6{player} &2释放了 &6{skill}'
  icon: 'RECORD_10'
  icon-data: 0
  icon-lore: 
  - '&d{name} &7({level}/{max})'
  - '&2种类: &6{type}'
  - ''
  - '{req:level}等级需求: {attr:level}'
  - '{req:cost}消耗技能点: {attr:cost}'
  - ''
  - '&2消耗法力值: {attr:mana}'
  - '&2冷却: {attr:cooldown}'
  - ''
  - '&7吹奏难听至极的乐章'
  - '&7给你的 &6{attr:are.radius} &7格内的敌人'
  - '&7造成 &6{attr:time.repetitions} &7次'
  - '&7每次&6{attr:damage.value}&7点的伤害'
  desc:  []
  components: 
    Cast: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        indicator: '2D'
      children: 
        Area-b: 
          type: 'target'
          indicator: '3D'
          data: 
            icon-key: 'are'
            radius-base: '3'
            radius-scale: '0.5'
            group: 'Enemy'
            wall: 'False'
            caster: 'False'
            max-base: '40'
            max-scale: '0'
            indicator: '2D'
          children: 
            Sound-c: 
              type: 'mechanic'
              indicator: '3D'
              data: 
                icon-key: ''
                counts: 'True'
                version: '1.9+'
                newsound: 'Entity Zombie Villager Ambient'
                volume-base: '100'
                volume-scale: '0'
                pitch-base: '1'
                pitch-scale: '0'
                indicator: '2D'
              children:  {}
            Sound-d: 
              type: 'mechanic'
              indicator: '3D'
              data: 
                icon-key: ''
                counts: 'True'
                version: '1.9+'
                newsound: 'Entity Zombie Villager Death'
                sound: 'Fizz'
                volume-base: '100'
                volume-scale: '0'
                pitch-base: '1'
                pitch-scale: '0'
                indicator: '2D'
              children:  {}
            Repeat-e: 
              type: 'mechanic'
              indicator: '3D'
              data: 
                icon-key: 'time'
                counts: 'True'
                repetitions-base: '2'
                repetitions-scale: '1'
                period: '1'
                delay: '0'
                indicator: '2D'
              children: 
                Damage-f: 
                  type: 'mechanic'
                  indicator: '3D'
                  data: 
                    icon-key: 'damage'
                    counts: 'True'
                    type: 'Damage'
                    value-base: '1'
                    value-scale: '0.5'
                    true: 'False'
                    classifier: 'default'
                    indicator: '2D'
                  children:  {}

and this is my skill

**Comment by Eniripsa96** [comment] 2017-10-08 15:00
Did you just invite them or did they also accept?

**Comment by SnUncle** [comment] 2017-10-08 15:03
im sure they accept

**Comment by SnUncle** [comment] 2017-10-08 15:03
im wating for you !

**Comment by SnUncle** [comment] 2017-10-08 15:03
this skill hit me too !

**Comment by SnUncle** [comment] 2017-10-09 00:44
I casted the skill from example named Horrible Cry 
It's still hit myself 

And i created a area buff skill ,its work for me but not work to my party member!

**Comment by SnUncle** [comment] 2017-10-09 00:56
I find why
when i set   parties-ally: 'true'  
the skill hit me and my teammembers!

**Comment by SnUncle** [comment] 2017-10-09 01:07
btw i can hurt my teammembers, and when i cast a skill target: Enemy ,my teammembers could be hurt

**Comment by Eniripsa96** [comment] 2017-10-09 02:54
Looks like there is a bug with the parties-ally setting. I'll fix it for 1.63

**Comment by SnUncle** [comment] 2017-10-09 03:06
i will wating for you update

**Comment by SnUncle** [comment] 2017-10-10 06:17
I don't know why .. but i downland skillapi 1.63 but “horrible cry" still hit me and my party members

and i can attack my party members too ....

**Comment by SnUncle** [comment] 2017-10-10 10:01
blacklist: 
  - 'IRON_BOOTS'
  - 'IRON_SWORD' 

And add some items to blacklist of my class 
but i still can use it 

:(

**Comment by Eniripsa96** [comment] 2017-10-10 14:20
What SkillAPI version does your server show on startup?

**Comment by SnUncle** [comment] 2017-10-11 01:26
1.63

**Comment by SnUncle** [comment] 2017-10-11 01:29
Could i send your my sever folder ? not any error in my back end

**Comment by SnUncle** [comment] 2017-10-11 01:32
all the area skill not work , and some skill target enemy can hurt my teammember :( i don't know why

**Comment by SnUncle** [comment] 2017-10-11 01:33
that make me cant use skillapi on my server

**Comment by Eniripsa96** [comment] 2017-10-11 04:29
I guess I would need to see your server setup since I am not sure why nothing would work for you seeing no one else including myself am seeing these problems.

**Comment by SnUncle** [comment] 2017-10-11 04:32
do you wanna check the config of skillapi?

**Comment by SnUncle** [comment] 2017-10-11 04:34
this is my plugin list:
EXXS
ESSxantibuild
essXchat
EssXprotect
EssXspawn
HolographicDisplays
Mccore
Parties
SkillAPI

**Comment by SnUncle** [comment] 2017-10-11 04:38
i think my problem is 
Parties not set my teammebers "ally"
because i can attack my pvp with my teammeber

**Comment by SnUncle** [comment] 2017-10-11 04:45
[plugins.zip](https://github.com/Eniripsa96/SkillAPI/files/1374215/plugins.zip)

**Comment by SnUncle** [comment] 2017-10-11 04:45
there is my plugin folder 
i running this plugin on spigot 1.12

**Comment by SnUncle** [comment] 2017-10-15 12:44
did you check the plugin folder?

**Comment by SnUncle** [comment] 2017-10-23 02:30
hello there ,  this problem still exist but i find some strange things 
when i reload skillapi after i set "parties-ally : true" in config ,my skill won't hit my ally
but if i restart the sever ,  my skill hit my ally and myself!

**Comment by Zicerite** [comment] 2018-06-19 06:17
I saw that this post had 25 comments, and i wanted to see what it was all about, but instead, its a super spammy issue report.

**I can confirm that, whatever your problem was before, no longer happens. I've tested it.**

Next time, do everyone a favor and at least **_edit_** your report, instead of continuous replying.

**Comment by Eniripsa96** [comment] 2018-06-19 13:18
Thanks for double checking Zicerite, will close the issue for now then, especially with how old this is. SnUncle, if you still having problems, feel free to open another issue.

**Closed by Eniripsa96** 2018-06-19 13:18 UTC
