### ISSUE TITLE
True Damage Mechanic kills citizens NPCS

### ISSUE THREAD

**Issue by Lix3nn53** [Eniripsa96/SkillAPI#320] opened 2018-07-05 12:54 UTC
here is the skill

> components: 
    Cast: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        indicator: '2D'
      children: 
        Particle Animation-b: 
          type: 'mechanic'
          indicator: '3D'
          data: 
            icon-key: ''
            counts: 'True'
            steps: '1'
            frequency: '0.1'
            angle: '0'
            start: '0'
            duration-base: '0.5'
            duration-scale: '0'
            h-translation-base: '0'
            h-translation-scale: '0'
            v-translation-base: '0'
            v-translation-scale: '0'
            h-cycles: '1'
            v-cycles: '1'
            particle: 'Red Dust'
            arrangement: 'Sphere'
            radius-base: '1.2'
            radius-scale: '0'
            particles-base: '3'
            particles-scale: '0'
            visible-radius: '25'
            dx: '0.1'
            dy: '1'
            dz: '0.1'
            speed: '1'
            amount: '0'
            forward: '0'
            upward: '0.8'
            right: '0'
            indicator: '2D'
          children:  {}
        Command-c: 
          type: 'mechanic'
          indicator: '3D'
          data: 
            icon-key: ''
            counts: 'True'
            command: 'sesoynat aaoe'
            type: 'OP'
            indicator: '2D'
          children:  {}
        Projectile-d: 
          type: 'mechanic'
          indicator: '3D'
          data: 
            icon-key: 'pro'
            counts: 'True'
            projectile: 'Arrow'
            flaming: 'False'
            cost: ''
            group: 'Enemy'
            spread: 'Cone'
            amount-base: '6'
            amount-scale: '2'
            velocity-base: '3'
            velocity-scale: '0'
            angle-base: '120'
            angle-scale: '0'
            position: '0'
            forward-base: '-1'
            forward-scale: '0'
            upward-base: '0'
            upward-scale: '0'
            right-base: '0'
            right-scale: '0'
            use-effect: 'False'
            indicator: '2D'
          children: 
            Damage-e: 
              type: 'mechanic'
              indicator: '3D'
              data: 
                icon-key: 'dmg'
                counts: 'True'
                type: 'Damage'
                value-base: '40'
                value-scale: '35'
                true: 'False'
                classifier: 'water'
                indicator: '2D'
              children:  {}
            Potion-f: 
              type: 'mechanic'
              indicator: '3D'
              data: 
                icon-key: 'poi'
                counts: 'True'
                potion: 'Poison'
                ambient: 'False'
                tier-base: '0'
                tier-scale: '0'
                seconds-base: '8'
                seconds-scale: '2'
                indicator: '2D'
              children:  {}
            Repeat-g: 
              type: 'mechanic'
              indicator: '3D'
              data: 
                icon-key: ''
                counts: 'True'
                repetitions-base: '12'
                repetitions-scale: '2'
                period: '0.5'
                delay: '0.5'
                indicator: '2D'
              children: 
                Damage-h: 
                  type: 'mechanic'
                  indicator: '3D'
                  data: 
                    icon-key: 'poidmg'
                    counts: 'True'
                    type: 'Damage'
                    value-base: '4'
                    value-scale: '1.5'
                    true: 'True'
                    classifier: 'default'
                    indicator: '2D'
                  children:  {}

**Comment by Lix3nn53** [comment] 2018-07-06 02:01
[Yaylim Atisi.zip](https://github.com/Eniripsa96/SkillAPI/files/2168788/Yaylim.Atisi.zip)

**Comment by Lix3nn53** [comment] 2018-07-06 02:02
I fixed this issue with this code

> @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onPetGetDamage(TrueDamageEvent e) {
    	LivingEntity defender = e.getTarget();
    	if(defender.hasMetadata("NPC")){
    	    e.setCancelled(true);
	}
    }

**Comment by Eniripsa96** [comment] 2018-07-07 21:18
Closing as a duplicate of #321

**Closed by Eniripsa96** 2018-07-07 21:18 UTC
