### ISSUE TITLE
Kicked on class selection

### ISSUE THREAD

**Issue by doitliketyler** [Eniripsa96/SkillAPI#122] opened 2017-02-20 08:02 UTC
On a fresh install with 1 simple class I am getting kicked from the server as soon as I profess as that class. Im running a Paper Spigot 1.11.2 server on a Bungeecord network. No idea what is happening here. Thoughts?

**Comment by Eniripsa96** [comment] 2017-02-24 04:05
This is a duplicate of #88 and is related to BungeeCord. I will fix it if I find a cause, but it is a weird issue.

**Closed by Eniripsa96** 2017-02-24 04:05 UTC
