### ISSUE TITLE
"Durability" mechanic issue.

### ISSUE THREAD

**Issue by xxJinxedxx** [Eniripsa96/SkillAPI#474] opened 2019-06-30 23:35 UTC
SkillAPI Premium v1.87
Server version: paper spigot 1.8.8-R0.1

Issue: When using "Durability" mechanic Offhand set to False i get the following error message.
 - https://pastebin.com/1ryCXJUL

Again, if you need the skill i will send it via Discord.

**Comment by Eniripsa96** [comment] 2019-07-08 05:20
Duplicate of #476

**Closed by Eniripsa96** 2019-07-08 05:20 UTC
