### ISSUE TITLE
[BUG] Could not create own attributes

### ISSUE THREAD

**Issue by sumdream** [Eniripsa96/SkillAPI#204] opened 2017-11-09 12:40 UTC
I`m tring to create an my own attribute,but in  attr GUI only display default attr.
The lore-attributes is work fine.

**Comment by AngDrew** [comment] 2017-11-09 12:45
Maybe u have the same id like

Strength:

Strength: 

Vitality: 

Agility: 

Etc.

**Comment by DrkMatr1984** [comment] 2017-11-09 12:53
https://github.com/Eniripsa96/SkillAPI/issues/192

**Comment by sumdream** [comment] 2017-11-09 13:07
yeah it`s useful,THX!!!!
And more the attr does not work when I use right click to equip item but it work when use other way to equip.

**Comment by Eniripsa96** [comment] 2018-06-19 01:11
Closing due to age of the issue and being unable to reproduce the lingering problem. Feel free to re-open if you still need the help.

**Closed by Eniripsa96** 2018-06-19 01:11 UTC
