### ISSUE TITLE
Health bar Resets after a reconnection

### ISSUE THREAD

**Issue by rykea1** [Eniripsa96/SkillAPI#264] opened 2018-06-06 12:37 UTC
https://www.youtube.com/watch?v=Bad0X7ehg10&feature=youtu.be

I don't know what to do, please help

**Comment by Eniripsa96** [comment] 2018-06-16 05:18
Please provide more information. What is your configuration set up? What is happening in the console? What is the command you are running?

**Comment by Eniripsa96** [comment] 2018-06-19 00:57
Unable to reproduce, so closing the issue. Feel free to re-open if you're still having the issue, just provide the information requested above.

**Closed by Eniripsa96** 2018-06-19 00:57 UTC
