### ISSUE TITLE
"Durability" mechanic not working correctly?

### ISSUE THREAD

**Issue by xxJinxedxx** [Eniripsa96/SkillAPI#476] opened 2019-07-04 20:09 UTC
SkillAPI Premium v1.88
Server version: paper spigot 1.8.8-R0.1

Issue: Durability mechanic works, but only on the caster. I've tried to target the damaged entity (player) and it doesn't work.

Also in the Dynamic Editor when you open to edit the Durability mechanic we have this:
![Untitled](https://user-images.githubusercontent.com/13562136/60686179-fea1e900-9eaf-11e9-951e-df1781d1c15a.png)

If the value is not specified as a negative it will only increase the durability of the held item.
I'm not sure if this is a typo in the Dynamic Editor or not, this is why i've added it.

And lastly, if the negative value is not specified and the held item is with "full" durability or the specified value is bigger than the missing durability of the item there is this error message:
 - http://pasted.co/0db8c14f

**Comment by Eniripsa96** [comment] 2019-07-08 05:19
Durability mechanic was intended to only work on the caster and I'll avoid changing that until the rework to avoid breaking people's skills. 

The error message and removing items was fixed by 1.89.

The text in the editor should be updated, as yes, positive increases remaining durability.

**Closed by Eniripsa96** 2019-07-08 05:19 UTC
