### ISSUE TITLE
No Skills are showing up, please help!

### ISSUE THREAD

**Issue by rykea1** [Eniripsa96/SkillAPI#261] opened 2018-06-03 11:51 UTC
I've recently tried to create skills for a class but no matter what I do the result is the same and nothing shows up
![2018-06-03_13 45 56](https://user-images.githubusercontent.com/39830144/40886228-89ff47ae-6734-11e8-858c-07dde03896ba.png)

Dwarf: 
  name: 'Dwarf'
  prefix: '&7Dwarf'
  group: 'Race'
  mana: '&2Mana'
  max-level: 25
  parent: ''
  needs-permission: 'false'
  attributes: 
    health-base: '20'
    spirit-scale: '0'
    strength-base: '0'
    dexterity-base: '0'
    dexterity-scale: '0'
    mana-base: '20'
    health-scale: '0.5'
    vitality-scale: '0.5'
    spirit-base: '0'
    intelligence-scale: '0'
    strength-scale: '2'
    mana-scale: '0.5'
    vitality-base: '0'
    intelligence-base: '0'
  mana-regen: 1.0
  tree: 'BASIC_VERTICAL'
  skills: 
  - 'Dwarf Passives'
  - 'Forge Armor'
  - 'Quick Pick'
  - 'Splunker'
  - 'Mustard Grenade'
  - 'Molten Rock'
  icon: 'IRON_PICKAXE'
  icon-data: 0
  exp-source: 473
**SKILL** 
 name: 'Mustard Grenade'
  type: 'Gas'
  max-level: 100
  skill-req-lvl: 1
  needs-permission: 'false'
  combo: 'R R L'
  attributes: 
    cost-base: '1'
    cooldown-scale: '-0.1'
    incompatible: 
    - ''
    cost-scale: '0'
    level-scale: '0'
    level-base: '1'
    mana-base: '5'
    points-spent-req-base: '0'
    mana-scale: '0'
    cooldown-base: '20'
    points-spent-req-scale: '0'
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'FERMENTED_SPIDER_EYE'
  icon-data: 0
  icon-lore: 
  - '&d{name} &7({level}/{max})'
  - '&2Type: &6{type}'
  - ''
  - '{req:level}Level: {attr:level}'
  - '{req:cost}Cost: {attr:cost}'
  - ''
  - '&2Mana: {attr:mana}'
  - '&2Cooldown: {attr:cooldown}'
  desc:  []
  components: 
    Cast: 
      type: 'trigger'
      data: 
        icon-key: ''
      children: 
        Location-b: 
          type: 'target'
          data: 
            range-scale: '0.5'
            range-base: '15'
            icon-key: ''
            ground: 'True'
          children: 
            Item Projectile-c: 
              type: 'mechanic'
              data: 
                right-scale: '0'
                item: 'Monster Egg'
                forward-base: '0'
                right-base: '0'
                forward-scale: '0'
                counts: 'True'
                upward-scale: '0'
                amount-base: '1'
                spread: 'Cone'
                angle-scale: '0'
                use-effect: 'False'
                velocity-base: '3'
                icon-key: ''
                amount-scale: '0'
                position: '0'
                item-data: '0'
                angle-base: '30'
                upward-base: '0'
                velocity-scale: '0'
                group: 'Enemy'
              children: 
                Particle Projectile-d: 
                  type: 'mechanic'
                  data: 
                    right-scale: '0'
                    forward-base: '0'
                    counts: 'True'
                    upward-scale: '0'
                    lifespan: '3'
                    particles-base: '20'
                    radius-base: '4'
                    speed: '1'
                    frequency: '0.05'
                    arrangement: 'Circle'
                    use-effect: 'False'
                    dx: '0'
                    dy: '0'
                    dz: '0'
                    velocity-base: '3'
                    particle: 'Slime'
                    upward-base: '0'
                    pierce: 'False'
                    group: 'Enemy'
                    direction: 'XZ'
                    visible-radius: '25'
                    amount: '1'
                    right-base: '0'
                    forward-scale: '0'
                    radius-scale: '0'
                    particles-scale: '0'
                    amount-base: '1'
                    spread: 'Cone'
                    angle-scale: '0'
                    gravity: '0'
                    icon-key: ''
                    amount-scale: '0'
                    position: '0'
                    angle-base: '30'
                    velocity-scale: '0'
                  children: 
                    Sound-e: 
                      type: 'mechanic'
                      data: 
                        pitch-scale: '0'
                        counts: 'True'
                        volume-base: '100'
                        volume-scale: '0'
                        icon-key: ''
                        pitch-base: '1'
                        version: '1.9+'
                        newsound: 'Block Grass Break'
                      children:  {}
                    Potion-f: 
                      type: 'mechanic'
                      data: 
                        potion: 'Poison'
                        counts: 'True'
                        icon-key: ''
                        ambient: 'False'
                        tier-scale: '0'
                        seconds-scale: '0.1'
                        tier-base: '1'
                        seconds-base: '5'
                      children:  {}
                    Particle-g: 
                      type: 'mechanic'
                      data: 
                        visible-radius: '25'
                        amount: '1'
                        counts: 'True'
                        forward: '0'
                        radius-scale: '0'
                        particles-scale: '0'
                        particles-base: '20'
                        right: '0'
                        radius-base: '4'
                        speed: '1'
                        arrangement: 'Circle'
                        dx: '0'
                        dy: '0'
                        dz: '0'
                        icon-key: ''
                        particle: 'Explode'
                        direction: 'XZ'
                        upward: '0'
                      children:  {}
        Self-h: 
          type: 'target'
          data: 
            icon-key: ''
          children: 
            Potion-i: 
              type: 'mechanic'
              data: 
                potion: 'Invisibility'
                counts: 'True'
                icon-key: ''
                ambient: 'True'
                tier-scale: '0'
                seconds-scale: '0.1'
                tier-base: '1'
                seconds-base: '5'
              children:  {}

**Comment by Eniripsa96** [comment] 2018-06-16 06:06
Which SkillAPI version? If it's the premium version, try deleting "gui.yml". Otherwise, make sure the skills are being loaded on startup (check the console messages for number of skills loaded).

**Comment by Eniripsa96** [comment] 2018-06-19 01:05
Closing since I'm unable to reproduce the issue. Feel free to re-open if the above does not help, just provide the requested information.

**Closed by Eniripsa96** 2018-06-19 01:05 UTC
